# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-2cdcc9e1-b564-4874-bd3a-9cebcaef6f68";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-2cdcc9e1-b564-4874-bd3a-9cebcaef6f68".device = "/dev/disk/by-uuid/2cdcc9e1-b564-4874-bd3a-9cebcaef6f68";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B980-5ECD";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-74b91300-7897-45fa-813f-d58ab8d29db0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
